### ISSUE TITLE
create a real release

### ISSUE THREAD

**Issue by psifertex** [ImNotAVirus/delphi_ninja#4]
it looks like there's no actual release right now?

https://github.com/ImNotAVirus/delphi_ninja/releases

This breaks the plugin manager's ability to automatically update: 

https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release

**Comment by ImNotAVirus** [comment]
Sorry, it was a bad manipulation on my part. Is it fixed?
